export enum RequestAccountFilter {
  Id = 'id',
  Name = 'name',
  Email = 'email',
  Identification = 'identification',
  ModuleId = 'module.id',
  ModuleName = 'module.name',
  ModuleKey = 'module.key',
  ModuleDescription = 'module.description',
  ModuleEnabled = 'module.enabled',
  AccessProfileId = 'access_profile.id',
  AccessProfileName = 'access_profile.name',
  AccessProfileKey = 'access_profile.key',
  AccessProfileEnabled = 'access_profile.enabled',
  ModuleAccessRuleId = 'module_access_rule.id',
  ModuleAccessRuleTitle = 'module_access_rule.title',
  ModuleAccessRuleDescription = 'module_access_rule.description',
  ModuleAccessRuleKey = 'module_access_rule.key',
  CreatedAt = 'created_at',
  UpdatedAt = 'updated_at'
}
