export * from './create-entity-with-authentication.route'
export * from './delete-entity-by-id-with-authentication.route'
export * from './get-entity-by-id-with-authentication.route'
export * from './list-entities-with-authentication.route'
export * from './update-entity-by-id-with-authentication.route'
