export enum RepositoryFinanceAccountFilter {
  Id = '"finance_account"."id"',
  Name = '"finance_account"."name"',
  Type = '"finance_account"."type::text"',
  ClosingDate = 'date_trunc(\'day\',"finance_account"."closing_date")::text',
  DueDate = 'date_trunc(\'day\',"finance_account"."due_date")::text',
  CreditDate = 'date_trunc(\'day\',"finance_account"."credit_date")::text',
  DefaultCreditValue = '"finance_account"."default_credit_value"',
  DefaultCreditReleased = '"finance_account"."default_credit_released"',
  CreatedAt = 'date_trunc(\'day\',"finance_account"."created_at")::text',
  UpdatedAt = 'date_trunc(\'day\',"finance_account"."updated_at")::text',
  AccountId = '"account"."id"',
  AccountName = '"account"."name"',
  AccountEmail = '"account"."email"',
  AccountIdentification = '"account"."identification"',
  AccountCreatedAt = 'date_trunc(\'day\',"account"."created_at")::text',
  AccountUpdatedAt = 'date_trunc(\'day\',"account"."updated_at")::text',
  CompanyId = '"company"."id"',
  CompanyName = '"company"."name"',
  CompanyCreatedAt = 'date_trunc(\'day\',"company"."created_at")::text',
  CompanyUpdatedAt = 'date_trunc(\'day\',"company"."updated_at")::text'
}
